# Database settings.

database:
  driverClass: org.apache.derby.jdbc.ClientDriver
  user: admin
  password: P@ssw0rd
  url: jdbc:derby://localhost:1527/inventorydb
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ values 1"
  minSize: 8
  maxSize: 16
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

# server configuration
server:
  type: simple
  connector:
    type: http
    port: 8080